
// Mock data for patients and doctors

// 医生列表模拟数据
export const mockDoctors = [
  { name: "张医生", title: "主任医师", department: "内科/消化内科" },
  { name: "陈医生", title: "副主任医师", department: "外科/骨科" },
  { name: "王医生", title: "主治医师", department: "妇产科/产科" },
  { name: "李医生", title: "主任医师", department: "内科/心血管内科" },
  { name: "吴医生", title: "副主任医师", department: "耳鼻喉科" },
  { name: "刘医生", title: "主任医师", department: "外科/神经外科" },
  { name: "郑医生", title: "主治医师", department: "精神科" },
  { name: "孙医生", title: "副主任医师", department: "内科/呼吸内科" },
];

// 模拟数据
export const mockPatients = [
  {
    id: "P20230001",
    name: "王明",
    gender: "male",
    age: 35,
    birthDate: "1988-06-15",
    status: "waiting",
    registerTime: new Date(Date.now() - 15 * 60 * 1000), // 15分钟前
    department: "内科/消化内科",
    doctor: "张医生",
    doctorTitle: "主任医师",
    isMultipleDoctor: false,
    isSenior: false,
    hasPrescription: true,
  },
  {
    id: "P20230002",
    name: "李华",
    gender: "male",
    age: 28,
    birthDate: "1995-03-22",
    status: "in-treatment",
    registerTime: new Date(Date.now() - 45 * 60 * 1000), // 45分钟前
    department: "外科/骨科",
    doctor: "陈医生",
    doctorTitle: "副主任医师",
    isMultipleDoctor: false,
    isSenior: false,
    hasPrescription: false,
  },
  {
    id: "P20230003",
    name: "张丽",
    gender: "female",
    age: 42,
    birthDate: "1981-11-10",
    status: "completed",
    registerTime: new Date(Date.now() - 120 * 60 * 1000), // 2小时前
    department: "妇产科/产科",
    doctor: "王医生",
    doctorTitle: "主治医师",
    isMultipleDoctor: false,
    isSenior: false,
    hasPrescription: true,
  },
  {
    id: "P20230004",
    name: "赵伟",
    gender: "male",
    age: 65,
    birthDate: "1958-08-05",
    status: "waiting",
    registerTime: new Date(Date.now() - 10 * 60 * 1000), // 10分钟前
    department: "内科/心血管内科",
    doctor: "李医生",
    doctorTitle: "主任医师",
    isMultipleDoctor: true,
    isSenior: true,
    hasPrescription: false,
  },
  {
    id: "P20230005",
    name: "陈静",
    gender: "female",
    age: 31,
    birthDate: "1992-12-18",
    status: "in-treatment",
    registerTime: new Date(Date.now() - 30 * 60 * 1000), // 30分钟前
    department: "耳鼻喉科",
    doctor: "吴医生",
    doctorTitle: "副主任医师",
    isMultipleDoctor: false,
    isSenior: false,
    hasPrescription: true,
  },
  {
    id: "P20230006",
    name: "吴强",
    gender: "male",
    age: 53,
    birthDate: "1970-09-25",
    status: "waiting",
    registerTime: new Date(Date.now() - 5 * 60 * 1000), // 5分钟前
    department: "外科/神经外科",
    doctor: "刘医生",
    doctorTitle: "主任医师",
    isMultipleDoctor: false,
    isSenior: false,
    hasPrescription: false,
  },
  {
    id: "P20230007",
    name: "刘敏",
    gender: "other",
    age: 27,
    birthDate: "1996-04-30",
    status: "completed",
    registerTime: new Date(Date.now() - 180 * 60 * 1000), // 3小时前
    department: "精神科",
    doctor: "郑医生",
    doctorTitle: "主治医师",
    isMultipleDoctor: false,
    isSenior: false,
    hasPrescription: true,
  },
  {
    id: "P20230008",
    name: "周芳",
    gender: "female",
    age: 62,
    birthDate: "1961-07-12",
    status: "in-treatment",
    registerTime: new Date(Date.now() - 60 * 60 * 1000), // 1小时前
    department: "内科/呼吸内科",
    doctor: "孙医生",
    doctorTitle: "副主任医师",
    isMultipleDoctor: true,
    isSenior: true,
    hasPrescription: true,
  },
  // 张医生的15个新增患者（均匀分布在不同状态）
  // 5个候诊患者
  {
    id: "P20230009",
    name: "张志远",
    gender: "male",
    age: 45,
    birthDate: "1978-03-24",
    status: "waiting",
    registerTime: new Date(Date.now() - 12 * 60 * 1000),
    department: "内科/消化内科",
    doctor: "张医生",
    doctorTitle: "主任医师",
    isMultipleDoctor: false,
    isSenior: false,
    hasPrescription: false,
  },
  {
    id: "P20230010",
    name: "林小燕",
    gender: "female",
    age: 29,
    birthDate: "1994-07-18",
    status: "waiting",
    registerTime: new Date(Date.now() - 18 * 60 * 1000),
    department: "内科/消化内科",
    doctor: "张医生",
    doctorTitle: "主任医师",
    isMultipleDoctor: false,
    isSenior: false,
    hasPrescription: false,
  },
  {
    id: "P20230011",
    name: "陈大力",
    gender: "male",
    age: 57,
    birthDate: "1966-11-05",
    status: "waiting",
    registerTime: new Date(Date.now() - 25 * 60 * 1000),
    department: "内科/消化内科",
    doctor: "张医生",
    doctorTitle: "主任医师",
    isMultipleDoctor: false,
    isSenior: true,
    hasPrescription: false,
  },
  {
    id: "P20230012",
    name: "王丽丽",
    gender: "female",
    age: 33,
    birthDate: "1990-09-12",
    status: "waiting",
    registerTime: new Date(Date.now() - 8 * 60 * 1000),
    department: "内科/消化内科",
    doctor: "张医生",
    doctorTitle: "主任医师",
    isMultipleDoctor: false,
    isSenior: false,
    hasPrescription: false,
  },
  {
    id: "P20230013",
    name: "李强强",
    gender: "male",
    age: 41,
    birthDate: "1982-05-28",
    status: "waiting",
    registerTime: new Date(Date.now() - 32 * 60 * 1000),
    department: "内科/消化内科",
    doctor: "张医生",
    doctorTitle: "主任医师",
    isMultipleDoctor: false,
    isSenior: false,
    hasPrescription: false,
  },
  // 5个诊中患者
  {
    id: "P20230014",
    name: "徐婷婷",
    gender: "female",
    age: 26,
    birthDate: "1997-02-14",
    status: "in-treatment",
    registerTime: new Date(Date.now() - 55 * 60 * 1000),
    department: "内科/消化内科",
    doctor: "张医生",
    doctorTitle: "主任医师",
    isMultipleDoctor: false,
    isSenior: false,
    hasPrescription: false,
  },
  {
    id: "P20230015",
    name: "赵明明",
    gender: "male",
    age: 38,
    birthDate: "1985-08-22",
    status: "in-treatment",
    registerTime: new Date(Date.now() - 65 * 60 * 1000),
    department: "内科/消化内科",
    doctor: "张医生",
    doctorTitle: "主任医师",
    isMultipleDoctor: true,
    isSenior: false,
    hasPrescription: false,
  },
  {
    id: "P20230016",
    name: "周倩倩",
    gender: "female",
    age: 31,
    birthDate: "1992-04-10",
    status: "in-treatment",
    registerTime: new Date(Date.now() - 75 * 60 * 1000),
    department: "内科/消化内科",
    doctor: "张医生",
    doctorTitle: "主任医师",
    isMultipleDoctor: false,
    isSenior: false,
    hasPrescription: false,
  },
  {
    id: "P20230017",
    name: "刘建国",
    gender: "male",
    age: 67,
    birthDate: "1956-10-01",
    status: "in-treatment",
    registerTime: new Date(Date.now() - 85 * 60 * 1000),
    department: "内科/消化内科",
    doctor: "张医生",
    doctorTitle: "主任医师",
    isMultipleDoctor: false,
    isSenior: true,
    hasPrescription: false,
  },
  {
    id: "P20230018",
    name: "张丽娟",
    gender: "female",
    age: 45,
    birthDate: "1978-12-05",
    status: "in-treatment",
    registerTime: new Date(Date.now() - 95 * 60 * 1000),
    department: "内科/消化内科",
    doctor: "张医生",
    doctorTitle: "主任医师",
    isMultipleDoctor: false,
    isSenior: false,
    hasPrescription: false,
  },
  // 5个完成患者
  {
    id: "P20230019",
    name: "王志强",
    gender: "male",
    age: 52,
    birthDate: "1971-06-30",
    status: "completed",
    registerTime: new Date(Date.now() - 150 * 60 * 1000),
    department: "内科/消化内科",
    doctor: "张医生",
    doctorTitle: "主任医师",
    isMultipleDoctor: false,
    isSenior: true,
    hasPrescription: true,
  },
  {
    id: "P20230020",
    name: "李晓晓",
    gender: "female",
    age: 29,
    birthDate: "1994-11-22",
    status: "completed",
    registerTime: new Date(Date.now() - 165 * 60 * 1000),
    department: "内科/消化内科",
    doctor: "张医生",
    doctorTitle: "主任医师",
    isMultipleDoctor: false,
    isSenior: false,
    hasPrescription: true,
  },
  {
    id: "P20230021",
    name: "钱小宝",
    gender: "male",
    age: 6,
    birthDate: "2017-08-14",
    status: "completed",
    registerTime: new Date(Date.now() - 180 * 60 * 1000),
    department: "内科/消化内科",
    doctor: "张医生",
    doctorTitle: "主任医师",
    isMultipleDoctor: false,
    isSenior: false,
    hasPrescription: true,
  },
  {
    id: "P20230022",
    name: "郑美丽",
    gender: "female",
    age: 34,
    birthDate: "1989-03-25",
    status: "completed",
    registerTime: new Date(Date.now() - 195 * 60 * 1000),
    department: "内科/消化内科",
    doctor: "张医生",
    doctorTitle: "主任医师",
    isMultipleDoctor: false,
    isSenior: false,
    hasPrescription: true,
  },
  {
    id: "P20230023",
    name: "黄大山",
    gender: "male",
    age: 61,
    birthDate: "1962-12-08",
    status: "completed",
    registerTime: new Date(Date.now() - 210 * 60 * 1000),
    department: "内科/消化内科",
    doctor: "张医生",
    doctorTitle: "主任医师",
    isMultipleDoctor: false,
    isSenior: true,
    hasPrescription: true,
  },
];
